[workspace]
members = [
  "elevator",
  "lib/core/animation",
  "lib/core/asset",
  "lib/core/camera",
  "lib/core/floors",
  "lib/core/fps",
  "lib/core/person",
  "lib/core/physics",
  "lib/game/door",
  "lib/game/elevator",
  "lib/game/enemy",
  "lib/game/player",
  "lib/game/map",
]

